[tool.poetry]
name = "Platzi"
version = "1.3.0"
description = "The project contains folders related to the career of Machine Learning of Platzi"
authors = ["Marlon Menendez <marlon.menendezg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
tensorflow-macos = "^2.9.2"
tensorflow-metal = "^0.5.1"
jupyterlab = "^3.4.5"
matplotlib = "^3.5.3"
torch = "^1.12.1"
torchvision = "^0.13.1"
black = "^22.6.0"
flake8 = "^5.0.4"
scikit-image = "^0.19.3"
pandas = "^1.5.1"
seaborn = "^0.12.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
