[tool.poetry]
name = "Platzi-ML"
version = "1.2.1"
description = "Project with all the notebooks for all the courses in the ML career"
authors = ["Marlon Menendez <marlon.menendezg@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
tensorflow-macos = "^2.10.0"
tensorflow-metal = "^0.6.0"
jupyterlab = "^3.5.0"
matplotlib = "^3.6.2"
black = "^22.10.0"
flake8 = "^6.0.0"
seaborn = "^0.12.1"
nltk = "^3.8.1"
spacy = "^3.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
