[project]
name = "Platzi"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Marlon Menendez", email = "marlon.menendezg@gmail.com"}]
requires-python = ">= 3.11"
dependencies = [ "accelerate>=0.33.0,<0.34", "albumentations>=1.4.13,<1.5", "beautifulsoup4>=4.12.3,<4.13", "black>=24.8.0,<24.9", "chromadb>=0.5.5,<0.6", "click>=8.1.7,<8.2", "datasets>=2.20.0,<2.21", "diffusers>=0.29.2,<0.30", "evaluate>=0.4.2,<0.5", "fastapi>=0.112.0,<0.113", "flake8>=7.1.1,<7.2", "google-auth>=2.32.0,<2.33", "google-pasta>=0.2.0,<0.3", "googleapis-common-protos>=1.63.2,<1.64", "gradio-client>=1.2.0,<1.3", "gradio>=4.40.0,<4.41", "huggingface-hub>=0.24.5,<0.25", "icecream>=2.1.3,<2.2", "idna>=3.7,<4", "ipykernel>=6.29.5,<6.30", "ipython>=8.26.0,<8.27", "jedi>=0.19.1,<0.20", "jupyterlab>=4.2.4,<4.3", "kagglehub>=0.2.9,<0.3", "keras-core>=0.1.7,<0.2", "keras-nlp>=0.14.4,<0.15", "keras>=3.4.1,<3.5", "langchain>=0.2.12,<0.3", "langsmith>=0.1.98,<0.2", "markdown>=3.6,<4", "matplotlib>=3.9.0,<3.10", "nltk>=3.8.1,<3.9", "openai>=1.40.0,<1.41", "pandas>=2.2.2,<2.3", "pillow>=10.4.0,<10.5", "pinecone-client>=5.0.1,<5.1", "polars>=1.4.1,<1.5", "pylance>=0.16.0,<0.17", "ruff>=0.5.6,<0.6", "scikit-image>=0.24.0,<0.25", "scikit-learn>=1.5.1,<1.6", "seaborn>=0.13.2,<0.14", "tenacity>=8.5.0,<8.6", "tensorboard>=2.17.0,<2.18", "tensorflow-metal>=1.1.0,<1.2", "tensorflow-text>=2.17.0,<2.18", "tensorflow>=2.17.0,<2.18", "torch>=2.4.0,<2.5", "torchvision>=0.19.0,<0.20", "transformers>=4.44.0,<4.45", "uvicorn>=0.30.5,<0.31", "yellowbrick>=1.5,<2"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
Platzi = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.11.9.*"
